### ISSUE TITLE
cli-dns is incrementing SOA serial number by one when update-zone --overwrite is operating on input with an explicit SOA set

### ISSUE THREAD

**Issue by lanstreamer** [akamai/cli-dns#1]
Hi there - I'm not experienced with GO so can't work out where in the code the SOA serial number is getting incremented.

When specifying an explicit serial in a SOA record to update-zone with --overwrite I would expect the serial number of the zone in Fast DNS to end up being what is specified as long as what is specified is greater than the existing serial number.

However - I'm seeing that the SOA serial number in fast DNS is ending up being what was specified +1 which is problematic for my use case.

This might be a sensible default action when no SOA is specified, but when one is it doesn't seem correct to read the serial number and incremement it by one.

**Comment by dshafik** [comment]
This issue should be fixed, the new behavior is thus:
 
- If no SOA Is set (`0`) then it will use the current UNIX timestamp
- If the SOA has been unchanged since zone creation, then it will incremented by `1`
- If the SOA is any other value, it will retain the value

Thanks for your patience on resolving this. Please can you try again and confirm the behavior is as you'd like?

**Comment by dshafik** [comment]
I'm going to close this as no feedback has been given.
